### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yemh111** [0xZhangKe/WebSocketDemo#1]
java.lang.IllegalArgumentException: The scheme part is empty.
        at com.neovisionaries.ws.client.WebSocketFactory.isSecureConnectionRequired(WebSocketFactory.java:575)
        at com.neovisionaries.ws.client.WebSocketFactory.createSocket(WebSocketFactory.java:552)
        at com.neovisionaries.ws.client.WebSocketFactory.createSocket(WebSocketFactory.java:543)
        at com.neovisionaries.ws.client.WebSocketFactory.createSocket(WebSocketFactory.java:327)
        at com.neovisionaries.ws.client.WebSocketFactory.createSocket(WebSocketFactory.java:283)
        at com.zhangke.WebSocket.AbsBaseWebSocketService.setupWebSocket(AbsBaseWebSocketService.java:127)
        at com.zhangke.WebSocket.AbsBaseWebSocketService.access$100(AbsBaseWebSocketService.java:39)
        at com.zhangke.WebSocket.AbsBaseWebSocketService$WebSocketThread.run(AbsBaseWebSocketService.java:119)

**Comment by 0xZhangKe** [comment]
AbsBaseWebSocketService 是个抽象类，你需要创建一个类并继承它，同时实现抽象方法，看起来是因为你的子类中的 getConnectUrl() 没有返回 WebSocket 需要连接的 URL。
