### ISSUE TITLE
 I/NetworkChangedReceiver: 网络连接发生变化，当前WiFi连接可用，正在尝试重连。

### ISSUE THREAD

**Issue by AbrahamCaiJin** [0xZhangKe/WebSocketDemo#17]
I/NetworkChangedReceiver: 网络连接发生变化，当前WiFi连接可用，正在尝试重连。请问一直提示这个是什么意思？急

**Comment by AbrahamCaiJin** [comment]
E/WebSocketLib: WebSocketClient#onError(Exception)
                                                                     java.net.ConnectException: failed to connect to /172.168.2.188 (port 80): connect failed: ETIMEDOUT (Connection timed out)
                                                                         at libcore.io.IoBridge.connect(IoBridge.java:124)
                                                                         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                         at java.net.Socket.connect(Socket.java:938)
                                                                         at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:359)
                                                                         at java.lang.Thread.run(Thread.java:833)
                                                                      Caused by: android.system.ErrnoException: connect failed: ETIMEDOUT (Connection timed out)
                                                                         at libcore.io.Posix.connect(Native Method)
                                                                         at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
                                                                         at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
                                                                         at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
                                                                         at java.net.Socket.connect(Socket.java:938) 
                                                                         at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:359) 
                                                                         at java.lang.Thread.run(Thread.java:833)

**Comment by 0xZhangKe** [comment]
网络状态发生变化会自动连接，连接不上会提示这个。
