### ISSUE TITLE
fragment中使用时，老是报mWebSocketService空指针

### ISSUE THREAD

**Issue by feng612266** [0xZhangKe/WebSocketDemo#3]
java.lang.NullPointerException: Attempt to invoke interface method 'int com.modu.jgzsj.module.websocket.IWebSocket.getConnectStatus()' on a null object reference
        at com.modu.jgzsj.module.websocket.AbsBaseWebSocketFragment.sendText(AbsBaseWebSocketFragment.java:158)
        at com.modu.jgzsj.module.coin.trend.ChildTrendFragment.initView(ChildTrendFragment.java:300)
        at com.modu.jgzsj.base.baseImpl.BaseFragment.onCreateView(BaseFragment.java:85)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)

**Comment by 0xZhangKe** [comment]
服务绑定需要时间的，绑定完成后才能对 mWebSocketService 操作，如要在生命周期内进行操作需要先判断是否为空，如果想在刚打开时调用接口初始化数据可以在 onServiceBindSuccess() 方法中初始化。

**Comment by feng612266** [comment]
可以了，谢谢！

**Comment by feng612266** [comment]
这种方式是整个app共用一个websocket连接么，如果多个页面有websocket请求的话？

**Comment by 0xZhangKe** [comment]
对，整个 APP 共用一个 WebSocket 连接，因为是 APP 启动时就开启了一个 WebSocket 的服务，需要使用 WebSocket 的页面直接绑定这个服务即可。

**Comment by feng612266** [comment]
好的

**Comment by feng612266** [comment]
PS：我们可以在创建一个 BaseWebSocketServiceActivity 抽象类，实现其中的 Class<? extends AbsBaseWebSocketService> getWebSocketClass() 方法，因为在同一个 APP 中这个方法的返回值是一直不变的;您好，这个直接放抽象类或基类不是更好么，为何还要每个使用地方再写一次一样的代码

**Comment by feng612266** [comment]
您好，2.0版本准备做哪些更新或改动

**Comment by 0xZhangKe** [comment]
是可以这样的，会方便很多，2.0改动还是比较大的，首先更换了WebSocket的库，用了个使用人数更多的，另外实现方式等等改变也很大，这几天差不多能弄好。

**Comment by wang9090980** [comment]
请问，你现在更换的webSocket库的名字能否发一下

**Comment by 0xZhangKe** [comment]
org.java-websocket:Java-WebSocket

**Comment by wang9090980** [comment]
谢谢，请问你微信号是多少?或者是能否建立一个qq交流群

**Comment by 0xZhangKe** [comment]
加我微信吧：zke8888888
