### ISSUE TITLE
重连过程中会出现空指针

### ISSUE THREAD

**Issue by feng612266** [0xZhangKe/WebSocketDemo#6]
07-20 14:33:32.702 5935-6163/com.modu.jgzsj E/WebSocketLib: WebSocketClient#onError(Exception)
    java.net.SocketException: Socket is closed
        at java.net.Socket.setReuseAddress(Socket.java:1417)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:356)
        at java.lang.Thread.run(Thread.java:760)
07-20 14:33:32.702 5935-6163/com.modu.jgzsj I/WebSocketLib: 正在重连，请勿重复调用。
07-20 14:33:41.301 5935-6202/com.modu.jgzsj E/WebSocketLib: WebSocketClient#onError(Exception)
    java.net.SocketException: Socket is closed
        at java.net.Socket.setReuseAddress(Socket.java:1417)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:356)
        at java.lang.Thread.run(Thread.java:760)
07-20 14:33:41.302 5935-6202/com.modu.jgzsj I/WebSocketLib: 正在重连，请勿重复调用。
07-20 14:33:46.060 5935-5991/com.modu.jgzsj E/CrashReport: # CRASH STACK: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Thread.getId()' on a null object reference
        at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:269)
        at org.java_websocket.client.WebSocketClient.reconnect(WebSocketClient.java:222)
        at com.modu.jgzsj.module.websocket.WebSocketThread$WebSocketHandler.connect(WebSocketThread.java:175)
        at com.modu.jgzsj.module.websocket.WebSocketThread$WebSocketHandler.handleMessage(WebSocketThread.java:96)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at com.modu.jgzsj.module.websocket.WebSocketThread.run(WebSocketThread.java:60)
    #++++++++++++++++++++++++++++++++++++++++++#
public void connect() {
		if( writeThread != null )
			throw new IllegalStateException( "WebSocketClient objects are not reuseable" );
		writeThread = new Thread( this );
		writeThread.setName( "WebSocketConnectReadThread-" + writeThread.getId() );
		writeThread.start();
	}
库里面的，难道这个没有新建成功？
WebSocketThread.java文件中
Log.d(TAG, "WebSocket 开始重新连接..."); 
mWebSocket.reconnect();
是不是该调用下面方法进行重新连接
public void reconnect() { 
mReconnectManager.performReconnect(); 
}

**Comment by luotext** [comment]
貌似升级到1.3.9的库就好了。我之前引用1.3.8的也出现了。

**Comment by 0xZhangKe** [comment]
好的，谢谢。

**Comment by 0xZhangKe** [comment]
新版本已经解决
