### ISSUE TITLE
如何断开websocket连接？

### ISSUE THREAD

**Issue by jjjjbababy** [0xZhangKe/WebSocketDemo#62]
如何断开websocket连接？

**Comment by magoo-lau** [comment]
disConnect及destroy后立即重启会产生这个错误
java.lang.Exception: WebSocketEngine not start!
at com.zhangke.websocket.WebSocketEngine.connect(WebSocketEngine.java:49)
at com.zhangke.websocket.WebSocketManager.reconnectOnce(WebSocketManager.java:292)
at com.zhangke.websocket.DefaultReconnectManager$1.run(DefaultReconnectManager.java:97)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
